Started logging messages at Fri Dec 01 15:54:21 2017
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 10 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 62
Info:            Created 
Info:        Working on 63
Info:            Created 
Info:        Working on 81
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 77
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 13
Info:            Created 
Info:        Working on 99
Info:            Created 
Info:        Working on 123
Info:            Created 
Info:        Working on 17
Info:            Created 
Info:        Working on 25
Info:            Created 
Info:        Working on 143
Info:            Created 
Info:        Working on 144
Info:            Created 
Info:        Working on 157
Info:            Created 
Info:        Working on 158
Info:            Created 
Info:        Working on 42
Info:            Created 
Info:        Working on 155
Info:            Created 
Info:        Working on 164
Info:            Created 
Info:        Working on 66
Info:            Created 
Info:        Working on 149
Info:            Created 
Info:        Working on 166
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 109
Info:            Created 
Info:        Working on 125
Info:            Created 
Info:        Working on 86
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 2.40125e-005
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Fri Dec 01 15:54:21 2017
